# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35b232078c5aca49f07d92c066bb69cf7c9f9b18f1534b89c27dd94828f27e227716045d2d21d5294ce62bfb6a3fe40e0b749b5099e6748acfb54a26ab50dcb7

test:
  secret_key_base: ccd5bed55bff043fe789f358f8072307881bc8708f1c7d058daace224c54bf091828894d8b632025bcde30469f9890cb8e37aa284880033c66546d64ec1c8821

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
